name: Update YTDLP

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  check-update:
    runs-on: ubuntu-latest
    outputs:
      latest: ${{ steps.check-updates.outputs.latest }}
      current: ${{ steps.check-updates.outputs.current }}
    steps:
      - name: Check for YT-DLP updates
        id: check-updates
        run: |
          latest_version=$(curl -s https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest | jq -r .tag_name)
          current_version="${{ vars.YTDLP_CURRENT_VERSION }}"
          echo "latest=$latest_version" >> "$GITHUB_OUTPUT"
          echo "current=$current_version" >> "$GITHUB_OUTPUT"
        env:
          GH_TOKEN: ${{ secrets.VARIABLES_PAT }}

  build-and-push:
    if: ${{ needs.check-update.outputs.latest != needs.check-update.outputs.current }}
    runs-on: ubuntu-latest
    needs:
      - check-update

    permissions:
      contents: read
      packages: write
      id-token: write

    env:
      LATEST: ${{needs.check-update.outputs.latest}}
      CURRENT: ${{needs.check-update.outputs.current}}

    steps:
      - name: Print versions
        run: |
          echo "Latest:$LATEST, Current:$CURRENT"

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@988b5a0280414f521da01fcc63a27aeeb4b104db

      - name: Log in to the Container registry
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@8e5442c4ef9f78752691e2d8f8d19755c6f78e81
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=${{ needs.check-update.outputs.latest }}
            type=raw,value=latest

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@5cd11c3a4ced054e52742c5fd54dca954e0edd85
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Update current version
        run: |
          gh variable set YTDLP_CURRENT_VERSION --body "$LATEST"
        env:
          GH_TOKEN: ${{ secrets.VARIABLES_PAT }}
